---
config:
  theme: neo
---
flowchart TD
        A(["Start"])
        B(["Auth"])
        C(["Login"])
        D(["Register"])
        E(["ForgetPassword"])
        F(["Dashboard"])
        G(["Tashilat"])
        H(["Dashboard"])
        I(["Dashboard"])
        J(["Dashboard"])
        K(["Dashboard"])
        L(["Dashboard"])
        M(["Dashboard"])
        N(["Logout"])
        N --> C
        A --> B
        B --> C
        B --> D
        B --> E
        C --> F
        F --> G
        F --> H
        F --> I
        F --> J
        F --> K
        F --> L
        F --> M
