/**
 * Auth API service — uses clients generated by swagger-typescript-api (@/api).
 */
import { Auth } from '@/api/Auth'
import type { ILoginRequestDTO, IRefreshRequestDTO } from '@/api/data-contracts'
import { apiClient } from '@core/api/api.client'
import { AUTH_API_VERSION } from '../models/auth.const'
import type { AuthUser } from '../models/auth.model'

const authApi = new Auth(apiClient)


export const useAuthService = () => {
  const login = async (payload: ILoginRequestDTO): Promise<AuthUser> => {
    return await authApi.v1AuthLoginCreate({ version: AUTH_API_VERSION }, payload)
  }

  const refresh = async (payload: IRefreshRequestDTO): Promise<AuthUser> => {
    return await authApi.v1AuthRefreshTokenCreate({ version: AUTH_API_VERSION }, payload)
  }

  const validate = async (token: string): Promise<boolean> => {
    return await authApi.v1AuthValidateTokenCreate({ version: AUTH_API_VERSION }, { token })
  }
  return {
    login,
    refresh,
    validate,
  }
}


