import * as animate from 'animate.css'
import type { TransitionItem } from '@/types'
export const keys = Object.keys(animate)
export const transitionConfig: TransitionItem[] = [
  {
    name: 'bounce',
    icon: 'mdi:star',
    enterActive: 'animate__animated animate__bounce',
    leaveActive: 'animate__animated animate__bounce',
  },
  {
    name: 'slide-up',
    icon: 'mdi:arrow-up',
    enterActive: 'slide-up-enter-active',
    leaveActive: 'slide-up-leave-active',
    enterFrom: 'slide-up-enter-from',
    leaveTo: 'slide-up-leave-to',
  },
  {
    name: 'slide-down',
    icon: 'mdi:arrow-down',
    enterActive: 'slide-down-enter-active',
    leaveActive: 'slide-down-leave-active',
    enterFrom: 'slide-down-enter-from',
    leaveTo: 'slide-down-leave-to',
  },
  {
    name: 'slide-left',
    icon: 'mdi:arrow-left',
    enterActive: 'slide-left-enter-active',
    leaveActive: 'slide-left-leave-active',
    enterFrom: 'slide-left-enter-from',
    leaveTo: 'slide-left-leave-to',
  },
  {
    name: 'slide-right',
    icon: 'mdi:arrow-right',
    enterActive: 'slide-right-enter-active',
    leaveActive: 'slide-right-leave-active',
    enterFrom: 'slide-right-enter-from',
    leaveTo: 'slide-right-leave-to',
  },
  {
    name: 'fade',
    icon: 'mdi:weather-fog',
    enterActive: 'fade-enter-active',
    leaveActive: 'fade-leave-active',
    enterFrom: 'fade-enter-from',
    leaveTo: 'fade-leave-to',
  },
  {
    name: 'fade-slide',
    icon: 'mdi:arrow-expand',
    enterActive: 'fade-slide-enter-active',
    leaveActive: 'fade-slide-leave-active',
    enterFrom: 'fade-slide-enter-from',
    leaveTo: 'fade-slide-leave-to',
  },
  {
    name: 'fade-up',
    icon: 'mdi:arrow-up-bold',
    enterActive: 'fade-up-enter-active',
    leaveActive: 'fade-up-leave-active',
    enterFrom: 'fade-up-enter-from',
    leaveTo: 'fade-up-leave-to',
  },
  {
    name: 'fade-down',
    icon: 'mdi:arrow-down-bold',
    enterActive: 'fade-down-enter-active',
    leaveActive: 'fade-down-leave-active',
    enterFrom: 'fade-down-enter-from',
    leaveTo: 'fade-down-leave-to',
  },
  {
    name: 'fade-scale',
    icon: 'mdi:arrow-expand',
    enterActive: 'fade-scale-enter-active',
    leaveActive: 'fade-scale-leave-active',
    enterFrom: 'fade-scale-enter-from',
    leaveTo: 'fade-scale-leave-to',
  },
  {
    name: 'fade-slow',
    icon: 'mdi:weather-fog',
    enterActive: 'fade-slow',
    leaveActive: 'fade-slow',
  },
  {
    name: 'fade-slide-slow',
    icon: 'mdi:arrow-expand',
    enterActive: 'fade-slide-slow',
    leaveActive: 'fade-slide-slow',
  },
  {
    name: 'fade-up-slow',
    icon: 'mdi:arrow-up-bold',
    enterActive: 'fade-up-slow',
    leaveActive: 'fade-up-slow',
  },
  {
    name: 'fade-down-slow',
    icon: 'mdi:arrow-down-bold',
    enterActive: 'fade-down-slow',
    leaveActive: 'fade-down-slow',
  },
  {
    name: 'collapse',
    icon: 'mdi:chevron-down',
    enterActive: 'collapse-transition-enter-active',
    leaveActive: 'collapse-transition-leave-active',
    enterFrom: 'collapse-enter-from',
    leaveTo: 'collapse-leave-to',
  },
]
