/**
 * Auth API service — uses clients generated by swagger-typescript-api (@/api).
 */
import { Auth } from '@/api/Auth'
import type { ILoginRequestDTO, IRefreshRequestDTO } from '@/api/data-contracts'
import { apiClient } from '@core/api/api.client'

import { AUTH_API_VERSION } from '../models/auth.const'
import type { AuthUser } from '../models/auth.model'
import { unwrapLoginResponse } from '../utils/auth.util'
import { mapAuthUser } from './auth.mapper'

const authApi = new Auth(apiClient)

export const authService = {
  async login(payload: ILoginRequestDTO): Promise<AuthUser> {
    const response = await authApi.vAuthLoginCreate({ version: AUTH_API_VERSION }, payload)
    return mapAuthUser(unwrapLoginResponse(response))
  },

  async refresh(payload: IRefreshRequestDTO): Promise<AuthUser> {
    const response = await authApi.vAuthRefreshTokenCreate({ version: AUTH_API_VERSION }, payload)
    return mapAuthUser(unwrapLoginResponse(response))
  },

  async validate(token: string): Promise<boolean> {
    const response = await authApi.vAuthValidateTokenCreate(
      { version: AUTH_API_VERSION },
      { token },
    )
    return Boolean(response.data)
  },
}
